Change image format
fastruby/styleguide pull request #35
Opened 2022-11-15 18:41 UTC by hmdros

Addressing performance improvement suggested by lighthouse reports changed this image to .webp format in internal PR.

2022-11-28 15:52 UTC, kindoflew commented
Support for `webp` is pretty good (https://caniuse.com/webp), but I wonder if we should also have `jpeg` as a fallback, just in case? what do you think, @etagwerker?

2022-11-28 16:41 UTC, etagwerker commented
@kindoflew I like your idea 👍

2022-11-29 23:26 UTC, bronzdoc approved these changes

2022-12-01 12:55 UTC, hmdros commented
Thanks for the suggestions @kindoflew

I added this @supports CSS rule based on [this blog post](https://www.irigoyen.dev/blog/2021/02/11/image-fallbacks-in-css-using-supports/). Let me know if you have any other opinion.

2022-12-05 21:43 UTC, kindoflew commented on vendor/assets/stylesheets/fastruby/styleguide/4-molecules/_location.scss
> +  @supports (background-image: asset_url("bg-location-2.webp")) {
i think this logic might be backwards. if the `@supports` is `true`, shouldn't the `.webp` image be nested here?

2022-12-05 21:45 UTC, kindoflew commented on vendor/assets/stylesheets/fastruby/styleguide/4-molecules/_location.scss
> +    @supports (background-image: asset_url("bg-location-2.webp")) {
same as above.

2022-12-05 21:45 UTC, kindoflew commented on vendor/assets/stylesheets/fastruby/styleguide/4-molecules/_location.scss
> +    @supports (background-image: asset_url("bg-location.webp")) {
same as above.

2022-12-05 21:46 UTC, kindoflew requested changes
Good idea with `@supports`! I think the logic needs to be flipped, but that's it!

2022-12-06 18:46 UTC, hmdros commented
> Good idea with `@supports`! I think the logic needs to be flipped, but that's it!

Done! Thanks @kindoflew

2022-12-08 15:32 UTC, merged